name: test
on:
  push:
    - main
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
      steps:
        - name: Install dependencies
          run: npm
        - name: Test and coverage
          run: react-scripts test --coverageDirectory test-coverage --coverage --watchAll=false

