name: test
on:
  push:
    branches:
      - main
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: install
      - name: Test and coverage
        run: test-coverage

